In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [4]:
b=np.array([[6,7,8],[1,2,3],[9,100,10]])
print(b)

[[  6   7   8]
 [  1   2   3]
 [  9 100  10]]


In [5]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
d=np.random.random_integers(5,size=(3,3))
print(d)

[[5 3 2]
 [1 5 2]
 [3 4 2]]


<ipython-input-6-fe281e17d408>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  d=np.random.random_integers(5,size=(3,3))


In [7]:
import numpy as np
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)	
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [8]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [9]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[4.17867391 4.51631079 5.4088621  4.72734807 5.48260841 5.15419644
 4.85169272 4.8159724  5.06098944 5.5692761 ]


In [10]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
import numpy as np
e  = np.array([(4,5,6), (7,8,9)])
print(e)

[[4 5 6]
 [7 8 9]]


In [12]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [4 5 6]
Second row: [7 8 9]


In [13]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[4.42778772 4.91292769 4.86209565 5.01247885 5.5495559  5.95378451
 4.99727782 4.53671872 5.63177324 5.0137692 ]


In [14]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [15]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00  2.80575969e-16 -8.29646454e-16] [[-0.15115432 -0.72704996 -0.01128698 -0.250341  ]
 [-0.34923733 -0.28320876  0.42321091  0.69689908]
 [-0.54732033  0.16063243 -0.81256087 -0.64277516]
 [-0.74540333  0.60447363  0.40063694  0.19621708]]


In [17]:
#make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [18]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]


In [19]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

OSError: data.txt not found.

In [21]:
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])
print(x)
print(y)
print(x-y)
print(np.subtract(x,y))

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]
